# -- Главное меню --

[[main]]
  name = "обо мне"
  url = "/about/"
  weight = 10

[[main]]
  name = "проекты"
  url = "/projects/"
  weight = 20

# -- Меню в подвале --

[[footer]]
  name = "Теги"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Авторы"
  pageRef = "authors"
  weight = 20


